/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
} from "@alephium/web3";
import { default as DoneraContractJson } from "../Donera.ral.json";
import { getContractByCodeHash } from "./contracts";

// Custom types for the contract
export namespace DoneraTypes {
  export type Fields = {
    selfFundTemplateId: HexString;
    selfListingFee: bigint;
    selfDonationFee: bigint;
    selfDeadlineLimit: bigint;
    selfOwner: Address;
  };

  export type State = ContractState<Fields>;

  export type FundListedEvent = ContractEvent<{
    metadataUrl: HexString;
    beneficiary: Address;
    organizer: Address;
    goal: bigint;
    deadlineTimestamp: bigint;
    fundContractId: HexString;
  }>;
  export type DonationEvent = ContractEvent<{
    tokenId: HexString;
    amount: bigint;
    donor: Address;
    fundContractId: HexString;
  }>;
  export type FundFinalizedEvent = ContractEvent<{
    finalizer: Address;
    fundContractId: HexString;
  }>;

  export interface CallMethodTable {
    getListingFee: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    getDonationFee: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
}

class Factory extends ContractFactory<DoneraInstance, DoneraTypes.Fields> {
  getInitialFieldsWithDefaultValues() {
    return this.contract.getInitialFieldsWithDefaultValues() as DoneraTypes.Fields;
  }

  eventIndex = { FundListed: 0, Donation: 1, FundFinalized: 2 };
  consts = {
    DoneraError: { InvalidDeadline: BigInt(0) },
    OwnedError: { Forbidden: BigInt(90) },
  };

  at(address: string): DoneraInstance {
    return new DoneraInstance(address);
  }

  tests = {
    createFund: async (
      params: TestContractParamsWithoutMaps<
        DoneraTypes.Fields,
        {
          metadataUrl: HexString;
          beneficiary: Address;
          goal: bigint;
          deadlineTimestamp: bigint;
        }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "createFund", params);
    },
    donateToFund: async (
      params: TestContractParamsWithoutMaps<
        DoneraTypes.Fields,
        { fundContractId: HexString; tokenId: HexString; amount: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "donateToFund", params);
    },
    finalizeFund: async (
      params: TestContractParamsWithoutMaps<
        DoneraTypes.Fields,
        { fundContractId: HexString }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "finalizeFund", params);
    },
    upgrade: async (
      params: TestContractParamsWithoutMaps<
        DoneraTypes.Fields,
        { newCode: HexString }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "upgrade", params);
    },
    upgradeWithFields: async (
      params: TestContractParamsWithoutMaps<
        DoneraTypes.Fields,
        {
          newCode: HexString;
          newImmFieldsEncoded: HexString;
          newMutFieldsEncoded: HexString;
        }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "upgradeWithFields", params);
    },
    assertOwner: async (
      params: TestContractParamsWithoutMaps<
        DoneraTypes.Fields,
        { caller: Address }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "assertOwner", params);
    },
    setOwner: async (
      params: TestContractParamsWithoutMaps<
        DoneraTypes.Fields,
        { newOwner: Address }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "setOwner", params);
    },
    deriveFundPath: async (
      params: TestContractParamsWithoutMaps<
        DoneraTypes.Fields,
        {
          metadataUrl: HexString;
          beneficiary: Address;
          organizer: Address;
          goal: bigint;
          deadlineTimestamp: bigint;
        }
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "deriveFundPath", params);
    },
    withdraw: async (
      params: TestContractParamsWithoutMaps<
        DoneraTypes.Fields,
        { amount: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "withdraw", params);
    },
    setSelfFundTemplateId: async (
      params: TestContractParamsWithoutMaps<
        DoneraTypes.Fields,
        { newFundTemplateId: HexString }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "setSelfFundTemplateId", params);
    },
    getListingFee: async (
      params: Omit<
        TestContractParamsWithoutMaps<DoneraTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "getListingFee", params);
    },
    setListingFee: async (
      params: TestContractParamsWithoutMaps<
        DoneraTypes.Fields,
        { newListingFee: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "setListingFee", params);
    },
    getDonationFee: async (
      params: Omit<
        TestContractParamsWithoutMaps<DoneraTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "getDonationFee", params);
    },
    setDonationFee: async (
      params: TestContractParamsWithoutMaps<
        DoneraTypes.Fields,
        { newDonationFee: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "setDonationFee", params);
    },
    setSelfDeadlineLimit: async (
      params: TestContractParamsWithoutMaps<
        DoneraTypes.Fields,
        { newDeadlineLimit: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "setSelfDeadlineLimit", params);
    },
  };
}

// Use this object to test and deploy the contract
export const Donera = new Factory(
  Contract.fromJson(
    DoneraContractJson,
    "=5-1+14f41eb42=1-1+3426f427f=1-1+2=1-1+5=1+2a742f643=1+44311431=1-1+4327=1+33=1-2+433d=1+34a=1-2+1010=2-2+900=2-3+39=1+60=1+1=1-1+0=2+60216037e05=1+03=1-1+637=1+656=1+7=1-1+6546756e643a=1+07b0=1-1+20202020202073706=1+6e=1+a20656e=2-2+72792c0a20202020202=1+6d657=1+6=1+6=1-1+617=1+6=2+5726c3=1+2=2+52c=1-1+a2=1-1+2=1+2020202062656e65666=1+63696172793a2=2+e2c0a202020202020676f616c3a201b2c0a2020202020206=1+6561646c696e6554696d657374616d7=2+a2=1+060a202020207d=65+57e02402e63726561746546756e643a207b7370616e3a20737562436f6e7472616374506174682c2070617468486173683a20017d160=87+16087e02402863726561746546756e643a207b7370616e3a2066756e64437265617465642c2066756e6449643a20017d=39-1+c1600160116027e044039646f6e617465546f46756e643a207b0a2020202020207370616e3a20656e7472792c0a20202020202066756e64436f6e747261637449643a20112c0a202020202020746f6b656e49643a20102c0a202020202020616d6f756e743a20060a202020207d=93-1+f=14+160016017e03403c66696e616c697a6546756e643a207b0a2020202020207370616e3a2066696e616c697a652c0a20202020202066756e64436f6e747261637449643a20132c0a20202020202066696e616c697a65723a20060a202020207d=171-1+d=30+16057e02402e64657269766546756e64506174683a207b7370616e3a20656e636f64696e672c2070617468456e636f6465643a20017d=176",
    "8c0097a9443aec277e5d64bdd283db3c88af9a1371ea105a751fc7bfe7985f24"
  )
);

// Use this class to interact with the blockchain
export class DoneraInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<DoneraTypes.State> {
    return fetchContractState(Donera, this);
  }

  async getContractEventsCurrentCount(): Promise<number> {
    return getContractEventsCurrentCount(this.address);
  }

  subscribeFundListedEvent(
    options: EventSubscribeOptions<DoneraTypes.FundListedEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      Donera.contract,
      this,
      options,
      "FundListed",
      fromCount
    );
  }

  subscribeDonationEvent(
    options: EventSubscribeOptions<DoneraTypes.DonationEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      Donera.contract,
      this,
      options,
      "Donation",
      fromCount
    );
  }

  subscribeFundFinalizedEvent(
    options: EventSubscribeOptions<DoneraTypes.FundFinalizedEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      Donera.contract,
      this,
      options,
      "FundFinalized",
      fromCount
    );
  }

  subscribeAllEvents(
    options: EventSubscribeOptions<
      | DoneraTypes.FundListedEvent
      | DoneraTypes.DonationEvent
      | DoneraTypes.FundFinalizedEvent
    >,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvents(Donera.contract, this, options, fromCount);
  }

  methods = {
    getListingFee: async (
      params?: DoneraTypes.CallMethodParams<"getListingFee">
    ): Promise<DoneraTypes.CallMethodResult<"getListingFee">> => {
      return callMethod(
        Donera,
        this,
        "getListingFee",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getDonationFee: async (
      params?: DoneraTypes.CallMethodParams<"getDonationFee">
    ): Promise<DoneraTypes.CallMethodResult<"getDonationFee">> => {
      return callMethod(
        Donera,
        this,
        "getDonationFee",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
  };

  async multicall<Calls extends DoneraTypes.MultiCallParams>(
    calls: Calls
  ): Promise<DoneraTypes.MultiCallResults<Calls>> {
    return (await multicallMethods(
      Donera,
      this,
      calls,
      getContractByCodeHash
    )) as DoneraTypes.MultiCallResults<Calls>;
  }
}
