/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  ExecutableScript,
  ExecuteScriptParams,
  ExecuteScriptResult,
  Script,
  SignerProvider,
  HexString,
} from "@alephium/web3";
import { default as CreateFundScriptJson } from "../CreateFund.ral.json";
import { default as DonateToFundScriptJson } from "../DonateToFund.ral.json";
import { default as FinalizeFundScriptJson } from "../FinalizeFund.ral.json";
import { default as SetAttoListingFeeScriptJson } from "../SetAttoListingFee.ral.json";

export const CreateFund = new ExecutableScript<{
  donera: HexString;
  name: HexString;
  description: HexString;
  recipient: Address;
  goal: bigint;
  deadlineTimestamp: bigint;
}>(Script.fromJson(CreateFundScriptJson));
export const DonateToFund = new ExecutableScript<{
  donera: HexString;
  fundContractId: HexString;
  tokenId: HexString;
  amount: bigint;
}>(Script.fromJson(DonateToFundScriptJson));
export const FinalizeFund = new ExecutableScript<{
  donera: HexString;
  fundContractId: HexString;
}>(Script.fromJson(FinalizeFundScriptJson));
export const SetAttoListingFee = new ExecutableScript<{
  donera: HexString;
  newAttoFee: bigint;
}>(Script.fromJson(SetAttoListingFeeScriptJson));
