name: CI
 
on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]
 
jobs:
  build:
    name: Test and Lint
    timeout-minutes: 15
    runs-on: ubuntu-latest
    services:
      alephium:
        image: "alephium/alephium:v2.9.1"
        ports:
          - 19973:19973/tcp
          - 19973:19973/udp
          - 127.0.0.1:20973:20973
          - 127.0.0.1:21973:21973
          - 127.0.0.1:22973:22973
        env:
          ALEPHIUM_FILE_LOG_LEVEL: "DEBUG"
        options: >-
          --health-cmd "curl http://127.0.0.1:22973/infos/self-clique"
          --health-interval 10s
          --health-timeout 45s
          --health-retries 5
          --name alephium
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
          submodules: "true"
      - name: Copy node config to service
        run: |
          docker cp ./vendor/alephium-stack/devnet/devnet.conf alephium:/alephium-home/.alephium/user.conf
          docker restart alephium
      - uses: pnpm/action-setup@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Lint
        run: pnpm lint
      - name: Test
        run: npx turbo test
